// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/exchange.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Symbol struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExchangeName         string   `protobuf:"bytes,2,opt,name=ExchangeName,proto3" json:"ExchangeName,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Valid                bool     `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Symbol) Reset()         { *m = Symbol{} }
func (m *Symbol) String() string { return proto.CompactTextString(m) }
func (*Symbol) ProtoMessage()    {}
func (*Symbol) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678a54b61e3becc, []int{0}
}

func (m *Symbol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Symbol.Unmarshal(m, b)
}
func (m *Symbol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Symbol.Marshal(b, m, deterministic)
}
func (m *Symbol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Symbol.Merge(m, src)
}
func (m *Symbol) XXX_Size() int {
	return xxx_messageInfo_Symbol.Size(m)
}
func (m *Symbol) XXX_DiscardUnknown() {
	xxx_messageInfo_Symbol.DiscardUnknown(m)
}

var xxx_messageInfo_Symbol proto.InternalMessageInfo

func (m *Symbol) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Symbol) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *Symbol) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Symbol) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Symbol) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Exchange struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Supported            bool     `protobuf:"varint,2,opt,name=supported,proto3" json:"supported,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exchange) Reset()         { *m = Exchange{} }
func (m *Exchange) String() string { return proto.CompactTextString(m) }
func (*Exchange) ProtoMessage()    {}
func (*Exchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678a54b61e3becc, []int{1}
}

func (m *Exchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exchange.Unmarshal(m, b)
}
func (m *Exchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exchange.Marshal(b, m, deterministic)
}
func (m *Exchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exchange.Merge(m, src)
}
func (m *Exchange) XXX_Size() int {
	return xxx_messageInfo_Exchange.Size(m)
}
func (m *Exchange) XXX_DiscardUnknown() {
	xxx_messageInfo_Exchange.DiscardUnknown(m)
}

var xxx_messageInfo_Exchange proto.InternalMessageInfo

func (m *Exchange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Exchange) GetSupported() bool {
	if m != nil {
		return m.Supported
	}
	return false
}

type AlertReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExchangeName         string   `protobuf:"bytes,2,opt,name=ExchangeName,proto3" json:"ExchangeName,omitempty"`
	Req                  *Req     `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertReq) Reset()         { *m = AlertReq{} }
func (m *AlertReq) String() string { return proto.CompactTextString(m) }
func (*AlertReq) ProtoMessage()    {}
func (*AlertReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678a54b61e3becc, []int{2}
}

func (m *AlertReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertReq.Unmarshal(m, b)
}
func (m *AlertReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertReq.Marshal(b, m, deterministic)
}
func (m *AlertReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertReq.Merge(m, src)
}
func (m *AlertReq) XXX_Size() int {
	return xxx_messageInfo_AlertReq.Size(m)
}
func (m *AlertReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertReq.DiscardUnknown(m)
}

var xxx_messageInfo_AlertReq proto.InternalMessageInfo

func (m *AlertReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AlertReq) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *AlertReq) GetReq() *Req {
	if m != nil {
		return m.Req
	}
	return nil
}

type AlertRes struct {
	Req                  *AlertReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Price                float32   `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Message              string    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AlertRes) Reset()         { *m = AlertRes{} }
func (m *AlertRes) String() string { return proto.CompactTextString(m) }
func (*AlertRes) ProtoMessage()    {}
func (*AlertRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678a54b61e3becc, []int{3}
}

func (m *AlertRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertRes.Unmarshal(m, b)
}
func (m *AlertRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertRes.Marshal(b, m, deterministic)
}
func (m *AlertRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertRes.Merge(m, src)
}
func (m *AlertRes) XXX_Size() int {
	return xxx_messageInfo_AlertRes.Size(m)
}
func (m *AlertRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertRes.DiscardUnknown(m)
}

var xxx_messageInfo_AlertRes proto.InternalMessageInfo

func (m *AlertRes) GetReq() *AlertReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *AlertRes) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AlertRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Req struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Price                float32  `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678a54b61e3becc, []int{4}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Req) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Req) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*Symbol)(nil), "proto.Symbol")
	proto.RegisterType((*Exchange)(nil), "proto.Exchange")
	proto.RegisterType((*AlertReq)(nil), "proto.AlertReq")
	proto.RegisterType((*AlertRes)(nil), "proto.AlertRes")
	proto.RegisterType((*Req)(nil), "proto.Req")
}

func init() {
	proto.RegisterFile("pkg/proto/exchange.proto", fileDescriptor_a678a54b61e3becc)
}

var fileDescriptor_a678a54b61e3becc = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x14, 0xcc, 0xb6, 0x94, 0x5f, 0x79, 0xc0, 0xcf, 0x64, 0x35, 0x64, 0x43, 0x38, 0x60, 0x4f, 0xbd,
	0x08, 0x06, 0x4d, 0xbc, 0x78, 0x31, 0xc6, 0x03, 0x31, 0x31, 0x66, 0x49, 0xf4, 0xa2, 0x87, 0xd2,
	0x6e, 0xa0, 0x11, 0xe8, 0x9f, 0x5d, 0x8c, 0xdc, 0xfd, 0x36, 0x7e, 0x49, 0xd3, 0xb7, 0xbb, 0xfc,
	0x3b, 0x7a, 0x6a, 0x67, 0x76, 0xf6, 0xcd, 0xcc, 0x6b, 0x81, 0xe5, 0x1f, 0xb3, 0x61, 0x5e, 0x66,
	0x2a, 0x1b, 0x8a, 0xaf, 0x78, 0x1e, 0xad, 0x66, 0x62, 0x80, 0x90, 0x7a, 0xf8, 0x08, 0xbe, 0x09,
	0xd4, 0x27, 0x9b, 0xe5, 0x34, 0x5b, 0xd0, 0xff, 0xe0, 0xa4, 0x09, 0x23, 0x7d, 0x12, 0x7a, 0xdc,
	0x49, 0x13, 0x1a, 0x40, 0xeb, 0xc1, 0xdc, 0x79, 0x8a, 0x96, 0x82, 0x39, 0x7d, 0x12, 0x36, 0xf8,
	0x01, 0x47, 0x3b, 0xf6, 0x36, 0x73, 0xf1, 0xd4, 0xce, 0x3a, 0x03, 0xef, 0x33, 0x5a, 0xa4, 0x09,
	0xab, 0xf5, 0x49, 0xe8, 0x73, 0x0d, 0x28, 0x83, 0x7f, 0x4b, 0x21, 0x65, 0x34, 0x13, 0xcc, 0x43,
	0xb9, 0x85, 0xc1, 0x2d, 0xf8, 0x76, 0x2e, 0xa5, 0x50, 0x43, 0x3f, 0x82, 0x12, 0x7c, 0xa7, 0x3d,
	0x68, 0xc8, 0x75, 0x9e, 0x67, 0xa5, 0x12, 0x09, 0x06, 0xf1, 0xf9, 0x8e, 0x08, 0xde, 0xc0, 0xbf,
	0x5b, 0x88, 0x52, 0x71, 0x51, 0xfc, 0xa9, 0x45, 0x0f, 0xdc, 0x52, 0x14, 0x58, 0xa1, 0x39, 0x02,
	0xbd, 0xa0, 0x01, 0x17, 0x05, 0xaf, 0xe8, 0xe0, 0x7d, 0x3b, 0x5d, 0xd2, 0x73, 0xad, 0x24, 0xa8,
	0x3c, 0x31, 0x4a, 0xeb, 0x8d, 0xf2, 0xaa, 0x7a, 0x5e, 0xa6, 0xb1, 0x76, 0x72, 0xb8, 0x06, 0xfb,
	0xd5, 0xdd, 0xc3, 0xea, 0x8f, 0xe0, 0x56, 0xb9, 0x3b, 0x50, 0x97, 0x7a, 0x93, 0xba, 0xb7, 0x41,
	0x15, 0x1f, 0xc5, 0x2a, 0xcd, 0x56, 0x26, 0xb9, 0x41, 0x3b, 0x1b, 0x77, 0xcf, 0x66, 0xf4, 0x43,
	0xa0, 0x79, 0x5f, 0x6e, 0x72, 0x95, 0xbd, 0x46, 0x2a, 0x9e, 0xd3, 0x6b, 0x68, 0x71, 0x51, 0xac,
	0x85, 0x54, 0xcf, 0x18, 0xe3, 0x38, 0x72, 0xf7, 0x88, 0x90, 0x21, 0xb9, 0x24, 0xf4, 0x06, 0x4e,
	0xc7, 0xd2, 0x6e, 0x68, 0x62, 0xd7, 0xbc, 0xbd, 0x6c, 0x4f, 0xba, 0xc7, 0x04, 0xbd, 0x80, 0xf6,
	0x58, 0xea, 0x5f, 0xe0, 0x05, 0xbf, 0x78, 0xdb, 0x28, 0x34, 0xd7, 0x3d, 0x84, 0xd3, 0x3a, 0xa2,
	0xab, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xa6, 0x1f, 0xbb, 0xa6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CryptoWatchClient is the client API for CryptoWatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CryptoWatchClient interface {
	RequestPrice(ctx context.Context, opts ...grpc.CallOption) (CryptoWatch_RequestPriceClient, error)
	IsExchangeSupported(ctx context.Context, in *Exchange, opts ...grpc.CallOption) (*Exchange, error)
	IsSymbolValid(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Symbol, error)
}

type cryptoWatchClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoWatchClient(cc grpc.ClientConnInterface) CryptoWatchClient {
	return &cryptoWatchClient{cc}
}

func (c *cryptoWatchClient) RequestPrice(ctx context.Context, opts ...grpc.CallOption) (CryptoWatch_RequestPriceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CryptoWatch_serviceDesc.Streams[0], "/proto.CryptoWatch/RequestPrice", opts...)
	if err != nil {
		return nil, err
	}
	x := &cryptoWatchRequestPriceClient{stream}
	return x, nil
}

type CryptoWatch_RequestPriceClient interface {
	Send(*AlertReq) error
	Recv() (*AlertRes, error)
	grpc.ClientStream
}

type cryptoWatchRequestPriceClient struct {
	grpc.ClientStream
}

func (x *cryptoWatchRequestPriceClient) Send(m *AlertReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cryptoWatchRequestPriceClient) Recv() (*AlertRes, error) {
	m := new(AlertRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cryptoWatchClient) IsExchangeSupported(ctx context.Context, in *Exchange, opts ...grpc.CallOption) (*Exchange, error) {
	out := new(Exchange)
	err := c.cc.Invoke(ctx, "/proto.CryptoWatch/IsExchangeSupported", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoWatchClient) IsSymbolValid(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Symbol, error) {
	out := new(Symbol)
	err := c.cc.Invoke(ctx, "/proto.CryptoWatch/IsSymbolValid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoWatchServer is the server API for CryptoWatch service.
type CryptoWatchServer interface {
	RequestPrice(CryptoWatch_RequestPriceServer) error
	IsExchangeSupported(context.Context, *Exchange) (*Exchange, error)
	IsSymbolValid(context.Context, *Symbol) (*Symbol, error)
}

// UnimplementedCryptoWatchServer can be embedded to have forward compatible implementations.
type UnimplementedCryptoWatchServer struct {
}

func (*UnimplementedCryptoWatchServer) RequestPrice(srv CryptoWatch_RequestPriceServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestPrice not implemented")
}
func (*UnimplementedCryptoWatchServer) IsExchangeSupported(ctx context.Context, req *Exchange) (*Exchange, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsExchangeSupported not implemented")
}
func (*UnimplementedCryptoWatchServer) IsSymbolValid(ctx context.Context, req *Symbol) (*Symbol, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsSymbolValid not implemented")
}

func RegisterCryptoWatchServer(s *grpc.Server, srv CryptoWatchServer) {
	s.RegisterService(&_CryptoWatch_serviceDesc, srv)
}

func _CryptoWatch_RequestPrice_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CryptoWatchServer).RequestPrice(&cryptoWatchRequestPriceServer{stream})
}

type CryptoWatch_RequestPriceServer interface {
	Send(*AlertRes) error
	Recv() (*AlertReq, error)
	grpc.ServerStream
}

type cryptoWatchRequestPriceServer struct {
	grpc.ServerStream
}

func (x *cryptoWatchRequestPriceServer) Send(m *AlertRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cryptoWatchRequestPriceServer) Recv() (*AlertReq, error) {
	m := new(AlertReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CryptoWatch_IsExchangeSupported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Exchange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoWatchServer).IsExchangeSupported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CryptoWatch/IsExchangeSupported",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoWatchServer).IsExchangeSupported(ctx, req.(*Exchange))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoWatch_IsSymbolValid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Symbol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoWatchServer).IsSymbolValid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CryptoWatch/IsSymbolValid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoWatchServer).IsSymbolValid(ctx, req.(*Symbol))
	}
	return interceptor(ctx, in, info, handler)
}

var _CryptoWatch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CryptoWatch",
	HandlerType: (*CryptoWatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsExchangeSupported",
			Handler:    _CryptoWatch_IsExchangeSupported_Handler,
		},
		{
			MethodName: "IsSymbolValid",
			Handler:    _CryptoWatch_IsSymbolValid_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestPrice",
			Handler:       _CryptoWatch_RequestPrice_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/exchange.proto",
}
